CREATE TABLE ENTEREDNUMBERS (ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,INTEGERVALUE INTEGER);
CREATE TABLE GCD (ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY, COMPUTED_GCD INTEGER);

